### ISSUE TITLE
Use of sphering for correction

### ISSUE THREAD

**Issue by jeskowagner** [carpenter-singh-lab/2023_Arevalo_NatComm_BatchCorrection#16]
@johnarevalo, as per #4 I understand sphering did not improve your results and you therefore removed it from the analysis. While reproducing your results for scenario 2, to me it looks like it's still being used, though.
After having removed the config definition from the `Snakefile`, running `snakemake -c1 --configfile inputs/conf/scenario_2.json`  yields:

```python
KeyError in file <...>2023_Arevalo_NatComm_BatchCorrection/rules/sphering.smk, line 11:                  
'sphering_method'                                                                                                                                     
  File "<...>2023_Arevalo_NatComm_BatchCorrection/Snakefile", line 26, in <module>                       
  File "<...>2023_Arevalo_NatComm_BatchCorrection/rules/correct.smk", line 1, in <module>                
  File "<...>2023_Arevalo_NatComm_BatchCorrection/rules/sphering.smk", line 11, in <module> 
```

Which seems to come from the inclusion of sphering in the `correct.smk` rules (line 1). Am I understanding correctly that this would best be removed?

**Comment by johnarevalo** [comment]
Thanks for catching this!

Sphering is not used, but it is imported to support other pipelines. Removing the import would fix the error you mentioned, but also break the support for sphering-based pipelines.

Changing the following line to `config.get("sphering_method")` will ignore sphering when not included:

https://github.com/carpenter-singh-lab/2023_Arevalo_NatComm_BatchCorrection/blob/04803d0b0620df5cc3b49daab5ccae4f69fc6b2d/rules/sphering.smk#L11

Please let me know if you are willing to try it and open a PR with the change.

**Comment by jeskowagner** [comment]
As per #17, thanks!
