### ISSUE TITLE
question about preprocessing

### ISSUE THREAD

**Issue by Chengwei-Yan** [carpenter-singh-lab/2023_Arevalo_NatComm_BatchCorrection#8]
Dear author, 
Dear author, because I haven't seen some specific modules like the preprocessing operation's pipeline,  I'm not quite sure if my understanding is correct. Is the preprocessing operation to first find the negative control, calculate the median and MAD value of the negative control, and then subtract the median of the negative control calculated from the whole dataset and divide it by the MAD value calculated from the negative control?
 Wish to receive your response as I have some confusion about this.

**Comment by johnarevalo** [comment]
Hi! Your description is correct, except the median and MAD are computed per plate. The normalization is also done per plate.
